### ISSUE TITLE
The number of threads increases each time dashboard page is reloaded.

### ISSUE THREAD

**Issue by sile** [pfnet/optuna#278]
When a dashboard page is loaded, a new thread is spawned for rendering the page (https://github.com/pfnet/optuna/blob/v0.5.0/optuna/dashboard.py#L208). However, this thread never dies even after the page is closed (maybe). Thus, each time a user reloads the dashboard page, the number of threads increases.
A thread will issue a query each second. So, this may overload the backend storage.

**Comment by sile** [comment]
For example, by repeating reloading, the following error occured in my environment:
```
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/foo/.local/lib/python3.5/site-packages/optuna/dashboard.py", line 213, in thread_loop
    new_trials = self.study.trials
  File "/home/foo/.local/lib/python3.5/site-packages/optuna/study.py", line 161, in trials
    return self.storage.get_all_trials(self.study_id)
  File "/home/foo/.local/lib/python3.5/site-packages/optuna/storages/rdb/storage.py", line 400, in get_all_trials
    study = models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/home/foo/.local/lib/python3.5/site-packages/optuna/storages/rdb/models.py", line 52, in find_or_raise_by_id
    study = cls.find_by_id(study_id, session)
  File "/home/foo/.local/lib/python3.5/site-packages/optuna/storages/rdb/models.py", line 43, in find_by_id
    study = session.query(cls).filter(cls.study_id == study_id).one_or_none()
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
    ret = list(self)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances
    close_with_result=True)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3025, in _get_bind_args
    **kw
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3007, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1046, in connection
    execution_options=execution_options)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1051, in _connection_for_bind
    engine, execution_options)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/home/foo/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1186, in _do_get
    (self.size(), self.overflow(), self._timeout), code="3o7r")
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

**Comment by hvy** [comment]
This issue still seem unaddressed.
