### ISSUE TITLE
error on running multiple processes in parallel

### ISSUE THREAD

**Issue by Delphi89** [pfnet/optuna#390]
Hi,

I've downloaded Optuna today (April 30) and run 3 processes in parallel, 2 from console and one from Jupiter Notebook. Received this error:

[W 2019-04-30 21:19:01,904] Setting status of trial#26 as TrialState.FAIL because of the following error: RuntimeError('unexpected EOF, expected 8 more bytes. The file might be corrupted.')
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\optuna\study.py", line 399, in _run_trial
    result = func(trial)
  File "<ipython-input-5-0fcdbd18b921>", line 53, in objective
    cnn.load_state_dict(torch.load('checkpoint.pt'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 8 more bytes. The file might be corrupted.

**Conditions**
- Optuna version: 0.10.0, downloaded on April 30
- Python version: 3.7
- OS: Win 10
- Machine Learning library to be optimized: Pytorch 1.1beta

I'm not using any database.

**Comment by Delphi89** [comment]
Sorry, I found the issue, all three instances tried to modify the same file in the same time.
