### ISSUE TITLE
params not being converted to internal_repr in FixedTrial suggest_* functions 

### ISSUE THREAD

**Issue by Rishav1** [pfnet/optuna#401]
FixedTrial's `_suggest` function is missing a call to `distribution.to_internal_repr` before line [L606.](https://github.com/pfnet/optuna/blob/master/optuna/trial.py#L606)

**Conditions**
- Optuna version: 0.11.0
- Python version: 3.5.2
- OS: Ubuntu 16.04
- Machine Learning library to be optimized:

**Code to reproduce**

```
>>> import optuna
>>> trial = optuna.trial.FixedTrial({'test': 'one'})
>>> trial.suggest_categorical('test', ['one', 'two'])
```

**Error messages, stack traces, or logs**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/pjt0/lib/python3.5/site-packages/optuna/trial.py", line 596, in suggest_categorical
    return self._suggest(name, distributions.CategoricalDistribution(choices=choices))
  File "/anaconda3/envs/pjt0/lib/python3.5/site-packages/optuna/trial.py", line 606, in _suggest
    if not distribution._contains(value):
  File "/anaconda3/envs/pjt0/lib/python3.5/site-packages/optuna/distributions.py", line 191, in _contains
    index = int(param_value_in_internal_repr)
ValueError: invalid literal for int() with base 10: 'one'
```

Just adding the following line works.

```
param_value_in_internal_repr = distribution.to_internal_repr(value)
if not distribution._contains(param_value_in_internal_repr):
    ...
```

**Comment by sile** [comment]
Thank you for reporting this problem!
I created a PR(https://github.com/pfnet/optuna/pull/402) to fix this.
