### ISSUE TITLE
ValueError when calling suggest_categorical with int and str

### ISSUE THREAD

**Issue by sushi30** [pfnet/optuna#448]
**Conditions**
- Optuna version: 0.13.0
- Python version: 3.7.3
- OS: Windows 10 Education
- Machine Learning library to be optimized: none

**Code to reproduce**
```
def objective(trial: optuna.Trial):
    x = trial.suggest_categorical("x", [1, "0"])
    print(x)
optuna.create_study( study_name="test_" + now_string(), storage="sqlite:///tmp/example.db").optimize(objective, n_trials=10)
```

**Error messages, stack traces, or logs**

```
Traceback (most recent call last):
  File "C:\Users\imri\github\scoring-model\venv\lib\site-packages\optuna\study.py", line 468, in _run_trial
    result = func(trial)
  File "~\github\scoring-model\tests\TestOptuna.py", line 12, in objective
    x = trial.suggest_categorical("x", [1, "0"])
  File "~\github\scoring-model\venv\lib\site-packages\optuna\trial.py", line 337, in suggest_categorical
    return self._suggest(name, distributions.CategoricalDistribution(choices=choices))
  File "~\github\scoring-model\venv\lib\site-packages\optuna\trial.py", line 457, in _suggest
    return self._set_new_param_or_get_existing(name, param_value, distribution)
  File "~\github\scoring-model\venv\lib\site-packages\optuna\trial.py", line 462, in _set_new_param_or_get_existing
    param_value_in_internal_repr = distribution.to_internal_repr(param_value)
  File "~\github\scoring-model\venv\lib\site-packages\optuna\distributions.py", line 236, in to_internal_repr
    return self.choices.index(param_value_in_external_repr)
ValueError: tuple.index(x): x not in tuple
```

**Comment by sile** [comment]
Thank you for reporting this problem.
This is a bug that we put in recently.
I created #449 for fixing this problem.
