### ISSUE TITLE
suggest_discrete_uniform error "unsupported operand type(s) for *: 'int' and 'NoneType'"

### ISSUE THREAD

**Issue by jbgh2** [pfnet/optuna#471]
**Conditions**
- Optuna version:
0.14.0

- Python version:
3.6.8

- OS:
Google Colab

- Machine Learning library to be optimized:
TensorFlow 2.0.0-beta1

**Code to reproduce**

The error started during a study run on Google Colab.
I don't have a min repro but can share the model sqlite DB and model code if needed.

**Error messages, stack traces, or logs**

```
[W 2019-08-05 19:12:03,795] Setting status of trial#27 as TrialState.FAIL because of the following error: TypeError("unsupported operand type(s) for *: 'int' and 'NoneType'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 469, in _run_trial
    result = func(trial)
  File "<ipython-input-42-176311fa1b08>", line 33, in objective
    model = make_trial_model(trial, input_shape)
  File "<ipython-input-17-3a5c1667bd48>", line 37, in make_trial_model
    embedding_size = trial.suggest_discrete_uniform('embedding_size', 100, 300, 50)
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial.py", line 268, in suggest_discrete_uniform
    return self._suggest(name, distribution)
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial.py", line 455, in _suggest
    study, trial, name, distribution)
  File "/usr/local/lib/python3.6/dist-packages/optuna/samplers/tpe/sampler.py", line 94, in sample_independent
    values, scores = _get_observation_pairs(study, param_name)
  File "/usr/local/lib/python3.6/dist-packages/optuna/samplers/tpe/sampler.py", line 523, in _get_observation_pairs
    score = (-step, sign * intermediate_value)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

**Comment by toshihikoyanase** [comment]
The cause seems to be `None` values in the intermediate values. Could you show us the code related to `trial.report()` if you use it?

**Comment by jbgh2** [comment]
I don't use `trial.report()`. Where could I add it to provide more info?
I tried downgrading to 0.13.0 and I haven't seen the problem since.

**Comment by toshihikoyanase** [comment]
> I don't use trial.report()

Hmm. The following message suggests the objective function reports intermediate values somewhere. 

```
  File "/usr/local/lib/python3.6/dist-packages/optuna/samplers/tpe/sampler.py", line 523, in _get_observation_pairs
    score = (-step, sign * intermediate_value)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

Another candidate is [`TensorFlowPruningHook`](https://github.com/pfnet/optuna/blob/master/optuna/integration/tensorflow.py) because you use TensorFlow and `TensorFlowPruningHook` reports the intermediate values. Do you use it in the objective function?

> Where could I add it to provide more info?

If you could attach the file containing your objective function to this issue, it would be a great help.

**Comment by jbgh2** [comment]
I do use the PruningHook so that would explain it. 
Here is the objective function and other functions that use `suggest`

```
def make_model(input_shape, n_hidden1=2049, n_hidden2=500, n_hidden3=180, batch_n_mom=0.99, dropout_rate=0.1):
    #Copy of simple denoising autoencoder model
    #Trying for same architecture as SDA example
    
    from tensorflow.keras.initializers import he_normal
    
    stacked_ae = keras.models.Sequential([
        keras.layers.Flatten(input_shape=input_shape),
        keras.layers.BatchNormalization(axis=1, momentum=batch_n_mom),
        
        keras.layers.Dense(n_hidden1, activation="selu", name="he1", kernel_initializer=he_normal(seed=27)),
        keras.layers.BatchNormalization(axis=1, momentum=batch_n_mom),
        keras.layers.Dropout(dropout_rate),
        
        keras.layers.Dense(n_hidden2, activation="selu", name="he2", kernel_initializer=he_normal(seed=42)),
        keras.layers.BatchNormalization(axis=1, momentum=batch_n_mom),
        
        keras.layers.Dense(n_hidden3, activation="selu", name="he3", kernel_initializer=he_normal(seed=65)),
        keras.layers.BatchNormalization(axis=1, momentum=batch_n_mom),
        
        keras.layers.Dense(n_hidden2, activation="selu", name="hd2", kernel_initializer=he_normal(seed=42)),
        keras.layers.BatchNormalization(axis=1, momentum=batch_n_mom),
        
        keras.layers.Dense(n_hidden1, activation="selu", name="hd1", kernel_initializer=he_normal(seed=27)),
        keras.layers.BatchNormalization(axis=1, momentum=batch_n_mom),
        keras.layers.Dropout(dropout_rate),
        
        keras.layers.Dense(input_shape[0] * input_shape[1], name="output", kernel_initializer=he_normal(seed=62)),
        keras.layers.Reshape(input_shape)
    ])
    
    return stacked_ae

def make_trial_model(trial, input_shape):

    #weight_decay = trial.suggest_loguniform('weight_decay', 1e-10, 1e-3)
    embedding_size = trial.suggest_discrete_uniform('embedding_size', 150, 300, 50)
    fan_out = trial.suggest_uniform('fan_out', 4.0, 10.0)
    dropout_rate = trial.suggest_uniform('dropout_rate', 0.1, 0.4)
    batch_norm_mom = trial.suggest_loguniform('batch_norm_mom', 0.7, 0.9999)
    
    hidden3 = embedding_size
    hidden2 = int(hidden3 * fan_out)
    hidden1 = int(hidden2 * fan_out)
    
    return make_model(input_shape, hidden1, hidden2, hidden3, batch_norm_mom, dropout_rate)

def create_optimizer(trial):
    # We optimize the choice of optimizers as well as their parameters.
    kwargs = {}
    optimizer_options = ['RMSProp', 'Adam', 'Adamax']
    optimizer_selected = trial.suggest_categorical('optimizer', optimizer_options)
    
    if optimizer_selected == 'RMSProp':
        kwargs['learning_rate'] = trial.suggest_loguniform('rmsprop_learning_rate', 1e-5, 1e-1)
        kwargs['rho'] = trial.suggest_uniform('rmsprop_rho', 0.85, 0.99)
        kwargs['momentum'] = trial.suggest_loguniform('rmsprop_momentum', 1e-5, 1e-1)
        
    elif optimizer_selected == 'Adam':
        kwargs['learning_rate'] = trial.suggest_loguniform('adam_learning_rate', 1e-5, 1e-1)

    elif optimizer_selected == 'Adamax':
        kwargs['learning_rate'] = trial.suggest_loguniform('adamax_learning_rate', 1e-5, 1e-1)
        
    elif optimizer_selected == 'Ftrl': #Not available on Colab. See https://github.com/googlecolab/colabtools/issues/669
        kwargs['learning_rate'] = trial.suggest_loguniform('momentum_opt_learning_rate', 1e-5, 1e-1)
        kwargs['learning_rate_power'] = trial.suggest_uniform('momentum_opt_momentum', -2.0, 0.0)

    optimizer = tf.keras.optimizers.get( { 'class_name': optimizer_selected, 'config': kwargs } )
    return optimizer
    
def objective_with_data(train_ds, test_ds, input_shape, epochs_per_trial, batches_per_epoch, score, save_model=False):
    # FYI: Objective functions can take additional arguments
    # (https://optuna.readthedocs.io/en/stable/faq.html#objective-func-additional-args).
    def objective(trial):

        print(f"Trial {trial.number}")
        
        # Build model and optimizer.
        model = make_trial_model(trial, input_shape)
        optimizer = create_optimizer(trial)
        callbacks = [OptunaKerasPruningCallback(trial, score)]

        #Compile
        model.compile(loss="mse",
              optimizer=optimizer,
              metrics=['accuracy'])

        # Training and validating cycle.
        history = model.fit(train_ds, 
                epochs=epochs_per_trial, steps_per_epoch=batches_per_epoch,
                validation_data=test_ds, validation_steps=batches_per_epoch,
                callbacks=callbacks, verbose=2)

        if save_model:
            model_path = os.path.join('models', f"ae_model_{datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}.h5")
            model.save(model_path)
        
        # Return last validation score.
        return history.history[score][-1] 
    
    return objective

**Comment by toshihikoyanase** [comment]
Thank you for sharing your source code. I understand that you are using the pruning hook for keras.

`OptunaKerasPruningCallback` seems to be your original implementation of pruning hook because the hook in Optuna is [`KerasPruningCallback`](https://optuna.readthedocs.io/en/stable/reference/integration.html#optuna.integration.KerasPruningCallback). If so, please make sure that [`trial.report()`](https://optuna.readthedocs.io/en/stable/reference/trial.html#optuna.trial.Trial.report) only reports `float` values.

**Comment by jbgh2** [comment]
My 'version' is just a copy of the original because I'm using TensorFlow's Keras and I was having import problems. 
I've been running version 0.13.0 for a few days without trouble. Could there be changes in 0.141.0 that could cause the problem?

**Comment by sile** [comment]
I think that #439 is the cause of this problem (v0.14.0 contains it).

Before merging #439 (i.e., v0.13.0 or older), `TPESampler` (the default sampler of Optuna) didn't consider pruned trials for suggesting (sampling) parameters. So, even if an invalid intermediate value (`None` in this case) is reported, it's simply ignored by `TPESampler`.

However, after merging #439, `TPESampler` became to consider pruned trials during sampling.
Thus, if intermediate values contain an invalid value, `TPESampler` raises an error as reported in this issue.

**Comment by toshihikoyanase** [comment]
> TensorFlow's Keras

I see. That's why you created `OptunaKerasPruningCallback`.
I'm testing the pruning callback with `tensorflow.keras`, but I couldn't reproduce the problem for now.

I'll share my notebook:
https://colab.research.google.com/drive/10e9n7CepXvkqHDHVbX3wSOUqTSglzErc#scrollTo=rUJp9z22mB_D&uniqifier=1

I'm not sure but I'm thinking that  `None` values in intermediate values were happened to be registered to the trial history while you were developing the pruning callback for `tensorflow.keras`.
Could you re-create a new study and try the optimization again?

**Comment by jbgh2** [comment]
Will do.

**Comment by jbgh2** [comment]
I've run several studies with 0.14.0 using new DBs and I haven't seen the problem again.
