### ISSUE TITLE
Error on importing optuna in Python 3.5.2

### ISSUE THREAD

**Issue by toshihikoyanase** [pfnet/optuna#509]
When I tried to use optuna in Python 3.5.2, I was not able to import optuna due to the error related to `pandas`. Currently, `pandas=0.25.0` is installed with `pip install optuna`, but it supports `Python>=3.5.3`. 

Currently, `pandas` is only required by `Study.trials_dataframe()`, and I think `pandas` can be optional because we can optimize objective functions without it.

**Workaround**
I can use optuna with `pandas==0.24.2` in Python 3.5.2. So, please downgrade pandas as a workaround.

```console
$ pip uninstall pandas
$ pip install pandas==0.24.2
```

**Conditions**
- Optuna version: 0.15.0
- Python version: 3.5.2
- OS: macOS High Sierra
- Machine Learning library to be optimized: N/A

**Code to reproduce**

```console
$ python
>>> import optuna
```

**Error messages, stack traces, or logs**

```console
>>> import optuna
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yanase/.pyenv/versions/optuna352/lib/python3.5/site-packages/optuna/__init__.py", line 2, in <module>
    from optuna import dashboard  # NOQA
  File "/Users/yanase/.pyenv/versions/optuna352/lib/python3.5/site-packages/optuna/dashboard.py", line 22, in <module>
    import optuna.study
  File "/Users/yanase/.pyenv/versions/optuna352/lib/python3.5/site-packages/optuna/study.py", line 7, in <module>
    import pandas as pd
  File "/Users/yanase/.pyenv/versions/optuna352/lib/python3.5/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/Users/yanase/.pyenv/versions/optuna352/lib/python3.5/site-packages/pandas/core/api.py", line 5, in <module>
...
  File "/Users/yanase/.pyenv/versions/3.5.2/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

**Comment by AlbinDavid** [comment]
$ pip uninstall pandas
$ pip install pandas==0.24.2
Is not working on python 3.5.2
