### ISSUE TITLE
Incompatibility with PySpark

### ISSUE THREAD

**Issue by roseaysina** [pfnet/optuna#571]
Hola! 

I discovered that optuna somehow is not compatible with PySpark. There is also a related question on [SO] and temporary fix.

[SO]: https://stackoverflow.com/q/58183158/4952975

If there is `import pyspark` before `import optuna` (just one line) then it fails with `n_trials > 1`. If reverse (optuna before spark) everything works fine. 

Here is the code: 
```python
# import pyspark  # uncomment to have an error
import optuna


def objective(trial: optuna.Trial):
    param = trial.suggest_uniform('param', 0, 100)
    return param


study = optuna.create_study()
study.optimize(objective, n_trials=3, n_jobs=1)
```

When I run this code with commented `import pyspark` I have three successful trials (even when `import pyspark` is after optuna import). If I run with uncommented import then I have failed trials except the first one: 

```
[I 2019-10-02 15:40:05,742] Finished trial#0 resulted in value: 49.07164288419234. Current best value is 49.07164288419234 with parameters: {'param': 49.07164288419234}.
[W 2019-10-02 15:40:05,743] Setting status of trial#1 as TrialState.FAIL because of the following error: AttributeError("'_BaseUniformDistribution' object has no attribute 'to_internal_repr'")
Traceback (most recent call last):
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/study.py", line 448, in _run_trial
    result = func(trial)
  File "/Users/roseaysina/code/test.py", line 6, in objective
    param = trial.suggest_uniform('param', 0, 100)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/trial.py", line 180, in suggest_uniform
    return self._suggest(name, distribution)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/trial.py", line 453, in _suggest
    self.study, trial, name, distribution)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/samplers/tpe/sampler.py", line 127, in sample_independent
    values, scores = _get_observation_pairs(study, param_name)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/samplers/tpe/sampler.py", line 558, in _get_observation_pairs
    param_value = distribution.to_internal_repr(trial.params[param_name])
AttributeError: '_BaseUniformDistribution' object has no attribute 'to_internal_repr'
[W 2019-10-02 15:40:05,771] Setting status of trial#2 as TrialState.FAIL because of the following error: AttributeError("'_BaseUniformDistribution' object has no attribute 'to_internal_repr'")
Traceback (most recent call last):
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/study.py", line 448, in _run_trial
    result = func(trial)
  File "/Users/roseaysina/code/test.py", line 6, in objective
    param = trial.suggest_uniform('param', 0, 100)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/trial.py", line 180, in suggest_uniform
    return self._suggest(name, distribution)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/trial.py", line 453, in _suggest
    self.study, trial, name, distribution)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/samplers/tpe/sampler.py", line 127, in sample_independent
    values, scores = _get_observation_pairs(study, param_name)
  File "/Users/roseaysina/anaconda3/envs/sauvage/lib/python3.7/site-packages/optuna/samplers/tpe/sampler.py", line 558, in _get_observation_pairs
    param_value = distribution.to_internal_repr(trial.params[param_name])
AttributeError: '_BaseUniformDistribution' object has no attribute 'to_internal_repr'
```

My environment: 
- Optuna version: `0.16.0`
- PySpark version: `2.4.4`
- Python version: `3.7.4`, Anaconda 3
- OS: macOS

Currently I am going to use fix with `RandomSampler` but I hope this strange (and almost uncatchable) bug will be fixed :) 

Thanks!

**Comment by sile** [comment]
Thank you for your detailed report.
I don't know the exact reason but it seems that after importing `pyspark`, Python cannot handle the multiple inheritance of [`UniformDistribution`](https://github.com/pfnet/optuna/blob/f50633a2392fd801021bb6b50dafc78550d71cbb/optuna/distributions.py#L89) class correctly.
To tackle this issue, I created a draft PR that makes `UniformDistribution` (and other distribution classes) single inheritance.
By applying this patch, I could run the following code without any errors:
```python
import pyspark
import optuna


def objective(trial: optuna.Trial):
    param = trial.suggest_uniform('param', 0, 100)
    return param


study = optuna.create_study()
study.optimize(objective, n_trials=3, n_jobs=1)
```

**Comment by roseaysina** [comment]
Thank you! That's amazing. I am really glad that this behaviour can be fixed in order to use optuna without fix. 
Thanks again :)
